theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
browser_spellcheck: true
theme_advanced_buttons1:
  - formatselect
  - fontselect
  - fontsizeselect
  - forecolor
  - backcolor
theme_advanced_buttons2:
  - hr  
  - sub
  - sup
  - charmap
  - separator
  - uploadimage
  - separator
  - cut
  - copy
  - paste
  - undo
  - redo
  - removeformat
  - cleanup
  - fullscreen  
  - help
  - code
theme_advanced_buttons3:
  - bold
  - italic
  - underline
  - strikethrough
  - separator
  - justifyleft
  - justifycenter
  - justifyright
  - justifyfull
  - separator
  - bullist
  - numlist
  - outdent
  - indent
  - blockquote
  - separator
  - link
  - unlink
  - anchor
plugins:
  - fullscreen
  - uploadimage
