theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
browser_spellcheck: true
convert_urls: false
theme_advanced_buttons1:
  - cut
  - copy
  - paste
  - undo
  - redo
  - separator
  - removeformat
  - cleanup
  - separator
  - fullscreen  
  - code
theme_advanced_buttons2:
  - uploadimage
  - separator
  - bold
  - italic
  - underline
  - strikethrough
  - separator
  - justifyleft
  - justifycenter
  - justifyright
  - justifyfull
  - separator
  - bullist
  - numlist
  - outdent
  - indent
  - blockquote
  - separator
  - link
  - unlink
  - anchor
plugins:
  - fullscreen
  - uploadimage
  - paste
content_css: /css/tinymce.css
paste_auto_cleanup_on_paste: true
